=== equisdots/palettes/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/equisdots/palettes/schema.json",
    "title": "equisdots palette",
    "description": "A palette file consumed by theme-sync. base16 colors plus optional background/foreground/role overrides.",
    "type": "object",
    "required": ["name", "slug", "base16"],
    "properties": {
        "name": {
            "type": "string",
            "description": "Display name shown by the desktop panel"
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z0-9][a-z0-9-]*$",
            "description": "Identifier (file name, theme ids, settings.json dock.palette)"
        },
        "author": {
            "type": "string"
        },
        "base16": {
            "type": "object",
            "required": [
                "color0", "color1", "color2", "color3", "color4", "color5",
                "color6", "color7", "color8", "color9", "color10", "color11",
                "color12", "color13", "color14", "color15"
            ],
            "properties": {
                "color0": {"$ref": "#/definitions/hex"},
                "color1": {"$ref": "#/definitions/hex"},
                "color2": {"$ref": "#/definitions/hex"},
                "color3": {"$ref": "#/definitions/hex"},
                "color4": {"$ref": "#/definitions/hex"},
                "color5": {"$ref": "#/definitions/hex"},
                "color6": {"$ref": "#/definitions/hex"},
                "color7": {"$ref": "#/definitions/hex"},
                "color8": {"$ref": "#/definitions/hex"},
                "color9": {"$ref": "#/definitions/hex"},
                "color10": {"$ref": "#/definitions/hex"},
                "color11": {"$ref": "#/definitions/hex"},
                "color12": {"$ref": "#/definitions/hex"},
                "color13": {"$ref": "#/definitions/hex"},
                "color14": {"$ref": "#/definitions/hex"},
                "color15": {"$ref": "#/definitions/hex"}
            },
            "additionalProperties": false
        },
        "background": {"$ref": "#/definitions/hex"},
        "foreground": {"$ref": "#/definitions/hex"},
        "roles": {
            "type": "object",
            "description": "Semantic role overrides applied on top of the base16 derivation",
            "additionalProperties": {"$ref": "#/definitions/hex"}
        }
    },
    "additionalProperties": true,
    "definitions": {
        "hex": {
            "type": "string",
            "pattern": "^#[0-9a-fA-F]{6}$"
        }
    }
}

=== equisdots/palettes/community/apathy.json
{
  "name": "Apathy",
  "slug": "apathy",
  "author": "Jannik Siebert (https://github.com/janniks)",
  "background": "#031A16",
  "foreground": "#81B5AC",
  "base16": {
    "color0": "#031A16",
    "color1": "#3E9688",
    "color2": "#883E96",
    "color3": "#3E4C96",
    "color4": "#3E7996",
    "color5": "#4C963E",
    "color6": "#963E4C",
    "color7": "#81B5AC",
    "color8": "#2B685E",
    "color9": "#3E9688",
    "color10": "#883E96",
    "color11": "#3E4C96",
    "color12": "#3E7996",
    "color13": "#4C963E",
    "color14": "#963E4C",
    "color15": "#D2E7E4"
  }
}

=== equisdots/palettes/community/catppuccin-frappe.json
{
  "name": "Catppuccin Frappe",
  "slug": "catppuccin-frappe",
  "author": "https://github.com/catppuccin/catppuccin",
  "background": "#303446",
  "foreground": "#c6d0f5",
  "base16": {
    "color0": "#303446",
    "color1": "#e78284",
    "color2": "#a6d189",
    "color3": "#e5c890",
    "color4": "#ef9f76",
    "color5": "#ca9ee6",
    "color6": "#81c8be",
    "color7": "#c6d0f5",
    "color8": "#51576d",
    "color9": "#e78284",
    "color10": "#a6d189",
    "color11": "#e5c890",
    "color12": "#ef9f76",
    "color13": "#ca9ee6",
    "color14": "#81c8be",
    "color15": "#babbf1"
  }
}

=== equisdots/palettes/cyberpunk-x.json
{
    "name": "Cyberpunk X",
    "slug": "cyberpunk-x",
    "author": "xscriptor",
    "base16": {
        "color0": "#07070c",
        "color1": "#fc618d",
        "color2": "#7bd88f",
        "color3": "#fce566",
        "color4": "#5ad4e6",
        "color5": "#948ae3",
        "color6": "#a3f3ff",
        "color7": "#f7f1ff",
        "color8": "#8b8892",
        "color9": "#fc618d",
        "color10": "#7bd88f",
        "color11": "#fce566",
        "color12": "#5ad4e6",
        "color13": "#948ae3",
        "color14": "#a3f3ff",
        "color15": "#f7f1ff"
    },
    "background": "#07070c",
    "foreground": "#f7f1ff",
    "roles": {
        "workspaceActive": "#eab308"
    }
}

=== equisdots/palettes/community/irblack.json
{
  "name": "IR Black",
  "slug": "irblack",
  "author": "Timothée Poisot (http://timotheepoisot.fr)",
  "background": "#000000",
  "foreground": "#b5b3aa",
  "base16": {
    "color0": "#000000",
    "color1": "#ff6c60",
    "color2": "#a8ff60",
    "color3": "#ffffb6",
    "color4": "#e9c062",
    "color5": "#ff73fd",
    "color6": "#c6c5fe",
    "color7": "#b5b3aa",
    "color8": "#6c6c66",
    "color9": "#ff6c60",
    "color10": "#a8ff60",
    "color11": "#ffffb6",
    "color12": "#e9c062",
    "color13": "#ff73fd",
    "color14": "#c6c5fe",
    "color15": "#fdfbee"
  }
}

=== equisdots/palettes/community/everforest-dark-hard.json
{
  "name": "Everforest Dark Hard",
  "slug": "everforest-dark-hard",
  "author": "Oskar Liew (https://github.com/OskarLiew)",
  "background": "#272e33",
  "foreground": "#d3c6aa",
  "base16": {
    "color0": "#272e33",
    "color1": "#7fbbb3",
    "color2": "#83c092",
    "color3": "#dbbc7f",
    "color4": "#d699b6",
    "color5": "#e67e80",
    "color6": "#e69875",
    "color7": "#d3c6aa",
    "color8": "#859289",
    "color9": "#7fbbb3",
    "color10": "#83c092",
    "color11": "#dbbc7f",
    "color12": "#d699b6",
    "color13": "#e67e80",
    "color14": "#e69875",
    "color15": "#fdf6e3"
  }
}

=== equisdots/palettes/community/atelier-sulphurpool.json
{
  "name": "Atelier Sulphurpool",
  "slug": "atelier-sulphurpool",
  "author": "Bram de Haan (http://atelierbramdehaan.nl)",
  "background": "#202746",
  "foreground": "#979db4",
  "base16": {
    "color0": "#202746",
    "color1": "#c94922",
    "color2": "#ac9739",
    "color3": "#c08b30",
    "color4": "#c76b29",
    "color5": "#6679cc",
    "color6": "#22a2c9",
    "color7": "#979db4",
    "color8": "#6b7394",
    "color9": "#c94922",
    "color10": "#ac9739",
    "color11": "#c08b30",
    "color12": "#c76b29",
    "color13": "#6679cc",
    "color14": "#22a2c9",
    "color15": "#f5f7ff"
  }
}

=== equisdots/palettes/community/catppuccin-macchiato.json
{
  "name": "Catppuccin Macchiato",
  "slug": "catppuccin-macchiato",
  "author": "https://github.com/catppuccin/catppuccin",
  "background": "#24273a",
  "foreground": "#cad3f5",
  "base16": {
    "color0": "#24273a",
    "color1": "#ed8796",
    "color2": "#a6da95",
    "color3": "#eed49f",
    "color4": "#f5a97f",
    "color5": "#c6a0f6",
    "color6": "#8bd5ca",
    "color7": "#cad3f5",
    "color8": "#494d64",
    "color9": "#ed8796",
    "color10": "#a6da95",
    "color11": "#eed49f",
    "color12": "#f5a97f",
    "color13": "#c6a0f6",
    "color14": "#8bd5ca",
    "color15": "#b7bdf8"
  }
}

=== equisdots/palettes/community/chalk.json
{
  "name": "Chalk",
  "slug": "chalk",
  "author": "Chris Kempson (http://chriskempson.com)",
  "background": "#151515",
  "foreground": "#d0d0d0",
  "base16": {
    "color0": "#151515",
    "color1": "#fb9fb1",
    "color2": "#acc267",
    "color3": "#ddb26f",
    "color4": "#eda987",
    "color5": "#e1a3ee",
    "color6": "#12cfc0",
    "color7": "#d0d0d0",
    "color8": "#505050",
    "color9": "#fb9fb1",
    "color10": "#acc267",
    "color11": "#ddb26f",
    "color12": "#eda987",
    "color13": "#e1a3ee",
    "color14": "#12cfc0",
    "color15": "#f5f5f5"
  }
}
