=== equisdots/palettes/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/equisdots/palettes/schema.json",
    "title": "equisdots palette",
    "description": "A palette file consumed by theme-sync. base16 colors plus optional background/foreground/role overrides.",
    "type": "object",
    "required": ["name", "slug", "base16"],
    "properties": {
        "name": {
            "type": "string",
            "description": "Display name shown by the desktop panel"
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z0-9][a-z0-9-]*$",
            "description": "Identifier (file name, theme ids, settings.json dock.palette)"
        },
        "author": {
            "type": "string"
        },
        "base16": {
            "type": "object",
            "required": [
                "color0", "color1", "color2", "color3", "color4", "color5",
                "color6", "color7", "color8", "color9", "color10", "color11",
                "color12", "color13", "color14", "color15"
            ],
            "properties": {
                "color0": {"$ref": "#/definitions/hex"},
                "color1": {"$ref": "#/definitions/hex"},
                "color2": {"$ref": "#/definitions/hex"},
                "color3": {"$ref": "#/definitions/hex"},
                "color4": {"$ref": "#/definitions/hex"},
                "color5": {"$ref": "#/definitions/hex"},
                "color6": {"$ref": "#/definitions/hex"},
                "color7": {"$ref": "#/definitions/hex"},
                "color8": {"$ref": "#/definitions/hex"},
                "color9": {"$ref": "#/definitions/hex"},
                "color10": {"$ref": "#/definitions/hex"},
                "color11": {"$ref": "#/definitions/hex"},
                "color12": {"$ref": "#/definitions/hex"},
                "color13": {"$ref": "#/definitions/hex"},
                "color14": {"$ref": "#/definitions/hex"},
                "color15": {"$ref": "#/definitions/hex"}
            },
            "additionalProperties": false
        },
        "background": {"$ref": "#/definitions/hex"},
        "foreground": {"$ref": "#/definitions/hex"},
        "roles": {
            "type": "object",
            "description": "Semantic role overrides applied on top of the base16 derivation",
            "additionalProperties": {"$ref": "#/definitions/hex"}
        }
    },
    "additionalProperties": true,
    "definitions": {
        "hex": {
            "type": "string",
            "pattern": "^#[0-9a-fA-F]{6}$"
        }
    }
}

=== equisdots/palettes/cyberpunk-night-city-mono-alt.json
{
    "name": "Cyberpunk Night City Mono Alt",
    "slug": "cyberpunk-night-city-mono-alt",
    "author": "xscriptor",
    "base16": {
        "color0": "#08070a",
        "color1": "#ff2a6d",
        "color2": "#2a2a2e",
        "color3": "#3a3a40",
        "color4": "#4a4a52",
        "color5": "#00b3ff",
        "color6": "#6a6a72",
        "color7": "#f0f0f5",
        "color8": "#88878b",
        "color9": "#ff2a6d",
        "color10": "#2a2a2e",
        "color11": "#3a3a40",
        "color12": "#4a4a52",
        "color13": "#00b3ff",
        "color14": "#6a6a72",
        "color15": "#f0f0f5"
    },
    "background": "#08070a",
    "foreground": "#f0f0f5",
    "roles": {
        "workspaceActive": "#ff2a6d",
        "accent": "#ff2a6d",
        "accent2": "#00b3ff"
    }
}

=== equisdots/palettes/community/github.json
{
  "name": "Github",
  "slug": "github",
  "author": "Defman21",
  "background": "#ffffff",
  "foreground": "#333333",
  "base16": {
    "color0": "#ffffff",
    "color1": "#ed6a43",
    "color2": "#183691",
    "color3": "#795da3",
    "color4": "#0086b3",
    "color5": "#a71d5d",
    "color6": "#183691",
    "color7": "#333333",
    "color8": "#969896",
    "color9": "#ed6a43",
    "color10": "#183691",
    "color11": "#795da3",
    "color12": "#0086b3",
    "color13": "#a71d5d",
    "color14": "#183691",
    "color15": "#ffffff"
  }
}

=== equisdots/palettes/cyberpunk-night-city-mono.json
{
    "name": "Cyberpunk Night City Mono",
    "slug": "cyberpunk-night-city-mono",
    "author": "xscriptor",
    "base16": {
        "color0": "#07070a",
        "color1": "#fcee0a",
        "color2": "#2a2a2e",
        "color3": "#3a3a40",
        "color4": "#4a4a52",
        "color5": "#00f0ff",
        "color6": "#6a6a72",
        "color7": "#f5f5f5",
        "color8": "#8a8a8b",
        "color9": "#fcee0a",
        "color10": "#2a2a2e",
        "color11": "#3a3a40",
        "color12": "#4a4a52",
        "color13": "#00f0ff",
        "color14": "#6a6a72",
        "color15": "#f5f5f5"
    },
    "background": "#07070a",
    "foreground": "#f5f5f5",
    "roles": {
        "workspaceActive": "#fcee0a",
        "accent": "#fcee0a",
        "accent2": "#00f0ff"
    }
}

=== equisdots/palettes/community/atelier-heath.json
{
  "name": "Atelier Heath",
  "slug": "atelier-heath",
  "author": "Bram de Haan (http://atelierbramdehaan.nl)",
  "background": "#1b181b",
  "foreground": "#ab9bab",
  "base16": {
    "color0": "#1b181b",
    "color1": "#ca402b",
    "color2": "#918b3b",
    "color3": "#bb8a35",
    "color4": "#a65926",
    "color5": "#7b59c0",
    "color6": "#159393",
    "color7": "#ab9bab",
    "color8": "#776977",
    "color9": "#ca402b",
    "color10": "#918b3b",
    "color11": "#bb8a35",
    "color12": "#a65926",
    "color13": "#7b59c0",
    "color14": "#159393",
    "color15": "#f7f3f7"
  }
}

=== equisdots/palettes/community/oceanicnext.json
{
  "name": "OceanicNext",
  "slug": "oceanicnext",
  "author": "https://github.com/voronianski/oceanic-next-color-scheme",
  "background": "#1B2B34",
  "foreground": "#C0C5CE",
  "base16": {
    "color0": "#1B2B34",
    "color1": "#EC5f67",
    "color2": "#99C794",
    "color3": "#FAC863",
    "color4": "#F99157",
    "color5": "#C594C5",
    "color6": "#5FB3B3",
    "color7": "#C0C5CE",
    "color8": "#65737E",
    "color9": "#EC5f67",
    "color10": "#99C794",
    "color11": "#FAC863",
    "color12": "#F99157",
    "color13": "#C594C5",
    "color14": "#5FB3B3",
    "color15": "#D8DEE9"
  }
}

=== equisdots/palettes/community/solarized-dark.json
{
  "name": "Solarized Dark",
  "slug": "solarized-dark",
  "author": "Ethan Schoonover (modified by aramisgithub)",
  "background": "#002b36",
  "foreground": "#93a1a1",
  "base16": {
    "color0": "#002b36",
    "color1": "#dc322f",
    "color2": "#859900",
    "color3": "#b58900",
    "color4": "#cb4b16",
    "color5": "#6c71c4",
    "color6": "#2aa198",
    "color7": "#93a1a1",
    "color8": "#657b83",
    "color9": "#dc322f",
    "color10": "#859900",
    "color11": "#b58900",
    "color12": "#cb4b16",
    "color13": "#6c71c4",
    "color14": "#2aa198",
    "color15": "#fdf6e3"
  }
}

=== equisdots/palettes/community/rebecca.json
{
  "name": "Rebecca",
  "slug": "rebecca",
  "author": "Victor Borja (http://github.com/vic) based on Rebecca Theme (http://github.com/vic/rebecca-theme)",
  "background": "#292a44",
  "foreground": "#f1eff8",
  "base16": {
    "color0": "#292a44",
    "color1": "#a0a0c5",
    "color2": "#6dfedf",
    "color3": "#ae81ff",
    "color4": "#efe4a1",
    "color5": "#7aa5ff",
    "color6": "#8eaee0",
    "color7": "#f1eff8",
    "color8": "#666699",
    "color9": "#a0a0c5",
    "color10": "#6dfedf",
    "color11": "#ae81ff",
    "color12": "#efe4a1",
    "color13": "#7aa5ff",
    "color14": "#8eaee0",
    "color15": "#53495d"
  }
}

=== equisdots/palettes/cyberpunk-netrunner.json
{
    "name": "Cyberpunk Netrunner",
    "slug": "cyberpunk-netrunner",
    "author": "xscriptor",
    "base16": {
        "color0": "#05070f",
        "color1": "#ff00c8",
        "color2": "#00ffcc",
        "color3": "#ffd319",
        "color4": "#0066ff",
        "color5": "#7a00ff",
        "color6": "#00f0ff",
        "color7": "#e6f7ff",
        "color8": "#818b93",
        "color9": "#ff00c8",
        "color10": "#00ffcc",
        "color11": "#ffd319",
        "color12": "#0066ff",
        "color13": "#7a00ff",
        "color14": "#00f0ff",
        "color15": "#e6f7ff"
    },
    "background": "#05070f",
    "foreground": "#e6f7ff",
    "roles": {
        "workspaceActive": "#ffd319"
    }
}
